import { existsSync, mkdirSync, readdirSync, copyFileSync, readFileSync, writeFileSync, chmodSync } from "fs";
import { join, dirname, relative } from "path";
import { fileURLToPath } from "url";
import { spawnSync } from "child_process";
import { ensureDashboardBuilt } from "../shared/build-dashboard.js";
import { installAxon, getPinnedVersion, getTargetTriple, checkAxonVersion } from "./axon-installer.js";

/** Local ensureDir — avoids cross-Mind import from cli/utils/fs. */
function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true });
}

// Resolve source directory — works with Bun (import.meta.dir) and Node.js (fileURLToPath fallback)
const _dir: string = (import.meta as { dir?: string }).dir
  ?? dirname(fileURLToPath(import.meta.url));

/**
 * Returns the path to the core Minds source directory (minds/).
 * Works in development (Bun, minds/installer/) and production (Node.js, dist/).
 */
export function getMindsSourceDir(): string {
  // Dev: minds/installer/../ = minds/
  const devPath = join(_dir, "..");
  if (existsSync(join(devPath, "server-base.ts"))) return devPath;
  // Built: dist/../minds/
  const builtPath = join(_dir, "..", "minds");
  if (existsSync(join(builtPath, "server-base.ts"))) return builtPath;
  throw new Error(
    "Minds source directory not found. Ensure the package was built with `bun run build`."
  );
}

/**
 * The core Mind subdirectories to copy into .minds/.
 *
 * Each entry here is a Mind (has server.ts/MIND.md) or a shared module
 * that Minds import at runtime.
 *
 * Intentionally EXCLUDED directories (not needed in target repos):
 *   - orchestrator  — empty dir, no source code
 *   - state         — runtime-generated data (SQLite DBs, JSON state), not source
 *   - templates     — scaffolding templates used by instantiate, not runtime code
 *   - fixtures      — test fixtures (mock Minds for discovery tests)
 *   - installer     — the installer itself, not installed into target repos
 *   - commands      — copied separately into .claude/commands/
 *   - skills        — copied separately into .claude/skills/
 *   - hooks         — copied separately into .claude/hooks/
 *   - tests         — dev-only test infrastructure
 */
const CORE_MINDS = [
  "router",
  "memory",
  "transport",
  "signals",
  "dashboard",
  "integrations",
  "observability",
  "instantiate",
  "fission",
  "pipeline_core",
  "execution",
  "coordination",
  "clarify",
  "pipelang",
  "spec_api",
] as const;

/** Shared infrastructure files/directories to copy into .minds/ */
const SHARED_INFRA_DIRS = ["shared", "contracts", "cli"] as const;
const SHARED_INFRA_FILES = [
  "server-base.ts",
  "mind.ts",
  "intent.ts",
  "bm25.ts",
  "router.ts",
  "discovery.ts",
  "embeddings.ts",
  "dispatch.ts",
  "generate-registry.ts",
  "STANDARDS.md",
] as const;

/** Claude Code slash commands to install: source filename -> destination filename */
const CLAUDE_COMMANDS: Array<{ src: string; dest: string }> = [
  { src: "tasks.md", dest: "minds.tasks.md" },
  { src: "implement.md", dest: "minds.implement.md" },
  { src: "drone.launch.md", dest: "minds.drone.launch.md" },
  { src: "fission.md", dest: "minds.fission.md" },
];

/** Dev artifacts that should never be copied from source into .minds/ */
const SKIP_COPY_NAMES = new Set(["node_modules", "dist", ".turbo", "bun.lock", "__tests__", "tests", "smoke-result.json"]);

/** Prefixes for test artifact directories generated by the test suite */
const SKIP_COPY_PREFIXES = ["_ta_", "_tb_", "_tc_", "_test_"];

/** Known Claude Code hook event types that can appear in settings.json */
const HOOK_EVENT_TYPES = new Set([
  "PreToolUse",
  "PostToolUse",
  "SessionStart",
  "SessionEnd",
  "UserPromptSubmit",
  "Stop",
  "SubagentStop",
]);

/** Log function type used by step helpers. */
type LogFn = (...args: unknown[]) => void;

/** Context passed to copy helpers and step functions. */
interface CopyContext {
  force: boolean;
  repoRoot: string;
  result: MindsInstallResult;
}

/**
 * Parse a hook filename to determine its event type.
 * Convention: `EventType.name.ts` or `EventType.name.hook.ts`
 * e.g. `PreToolUse.validate.ts` -> "PreToolUse"
 * Returns undefined if no known event type is found.
 */
function parseHookEventType(filename: string): string | undefined {
  const dotIndex = filename.indexOf(".");
  if (dotIndex === -1) return undefined;
  const prefix = filename.substring(0, dotIndex);
  return HOOK_EVENT_TYPES.has(prefix) ? prefix : undefined;
}

/**
 * Returns true if a hook file should be included (not a dotfile/gitkeep).
 * Shared predicate used by both getInstalledHookFiles and the hooks copy loop.
 */
function isHookFile(name: string): boolean {
  return name !== ".gitkeep" && !name.startsWith(".");
}

/** Returns true if the entry name matches any skip rule (exact, prefix, or suffix). */
function shouldSkipEntry(name: string): boolean {
  if (SKIP_COPY_NAMES.has(name)) return true;
  for (const prefix of SKIP_COPY_PREFIXES) {
    if (name.startsWith(prefix)) return true;
  }
  // Skip test files and SQLite databases
  if (name.endsWith(".test.ts") || name.endsWith(".test.js") || name.endsWith(".db")) return true;
  return false;
}

/**
 * Returns a list of actual hook filenames in the given directory,
 * filtering out .gitkeep and non-files.
 */
export function getInstalledHookFiles(hooksDir: string): string[] {
  if (!existsSync(hooksDir)) return [];
  return readdirSync(hooksDir).filter(isHookFile);
}

/**
 * Generate or merge Claude Code settings.json with hook registrations.
 *
 * Takes a list of hook filenames (e.g. ["PreToolUse.validate.ts"]) and
 * generates the hooks section of settings.json. If settingsPath points to
 * an existing file, its contents are preserved and hooks are merged.
 *
 * Hook filenames that don't match a known event type are skipped.
 */
export function generateClaudeSettings(
  hookFiles: string[],
  existingSettingsPath?: string,
): Record<string, unknown> {
  let settings: Record<string, unknown> = {};

  if (existingSettingsPath && existsSync(existingSettingsPath)) {
    try {
      settings = JSON.parse(readFileSync(existingSettingsPath, "utf-8")) as Record<string, unknown>;
    } catch {
      // If existing file is corrupt, start fresh
      settings = {};
    }
  }

  // Group hook files by event type
  const hooksByEvent = new Map<string, string[]>();
  for (const file of hookFiles) {
    const eventType = parseHookEventType(file);
    if (!eventType) continue;
    const existing = hooksByEvent.get(eventType) ?? [];
    existing.push(file);
    hooksByEvent.set(eventType, existing);
  }

  // Nothing to register
  if (hooksByEvent.size === 0) return settings;

  const existingHooks = (settings.hooks ?? {}) as Record<string, unknown[]>;

  for (const [eventType, files] of hooksByEvent) {
    const newEntries = files.map((file) => ({
      hooks: [
        {
          type: "command" as const,
          command: `.claude/hooks/${file}`,
        },
      ],
    }));

    const existing = existingHooks[eventType] ?? [];
    // Avoid duplicate registrations: skip entries whose command path is already present
    const existingCommands = new Set<string>();
    for (const entry of existing) {
      const hooks = (entry as Record<string, unknown>).hooks as Array<{ command?: string }> | undefined;
      if (hooks) {
        for (const h of hooks) {
          if (h.command) existingCommands.add(h.command);
        }
      }
    }

    const dedupedEntries = newEntries.filter((entry) => {
      const cmd = entry.hooks[0].command;
      return !existingCommands.has(cmd);
    });

    existingHooks[eventType] = [...existing, ...dedupedEntries];
  }

  settings.hooks = existingHooks;
  return settings;
}

export interface MindsInstallResult {
  copied: string[];
  skipped: string[];
  errors: string[];
  bunVerified: boolean;
  dashboardBuilt: boolean;
  axonInstalled: boolean;
}

/**
 * Copy a single file from src to dest, respecting force/skip semantics.
 * Tracks the result in copied/skipped arrays. Returns true if copied.
 * Optional postCopy callback for file-specific post-processing (e.g. chmod).
 */
function copyFileWithTracking(
  ctx: CopyContext,
  src: string,
  dest: string,
  opts?: { postCopy?: (destPath: string) => void },
): boolean {
  if (!ctx.force && existsSync(dest)) {
    ctx.result.skipped.push(relative(ctx.repoRoot, dest));
    return false;
  }
  copyFileSync(src, dest);
  if (opts?.postCopy) opts.postCopy(dest);
  ctx.result.copied.push(relative(ctx.repoRoot, dest));
  return true;
}

/** Recursively copy a directory, applying skip rules. */
function copyDirRecursive(ctx: CopyContext, src: string, dest: string): void {
  ensureDir(dest);
  for (const entry of readdirSync(src, { withFileTypes: true })) {
    if (shouldSkipEntry(entry.name)) continue;
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(ctx, srcPath, destPath);
    } else {
      copyFileWithTracking(ctx, srcPath, destPath);
    }
  }
}

// ---------------------------------------------------------------------------
// Step helpers — each handles one phase of installation
// ---------------------------------------------------------------------------

/** Step: Copy core Mind directories into .minds/ */
function installCoreMindDirs(ctx: CopyContext, mindsSourceDir: string, destMindsDir: string, log: LogFn): void {
  for (const mindName of CORE_MINDS) {
    const src = join(mindsSourceDir, mindName);
    if (!existsSync(src)) {
      log(`  Warning: Core Mind '${mindName}' not found at ${src}, skipping`);
      continue;
    }
    const dest = join(destMindsDir, mindName);
    copyDirRecursive(ctx, src, dest);
    log(`  Copied Mind: ${mindName}`);
  }
}

/** Step: Copy shared infrastructure directories */
function installSharedInfraDirs(ctx: CopyContext, mindsSourceDir: string, destMindsDir: string, _log: LogFn): void {
  for (const dir of SHARED_INFRA_DIRS) {
    const src = join(mindsSourceDir, dir);
    if (!existsSync(src)) continue;
    copyDirRecursive(ctx, src, join(destMindsDir, dir));
  }
}

/** Step: Copy shared infrastructure files */
function installSharedInfraFiles(ctx: CopyContext, mindsSourceDir: string, destMindsDir: string, _log: LogFn): void {
  for (const file of SHARED_INFRA_FILES) {
    const src = join(mindsSourceDir, file);
    if (!existsSync(src)) continue;
    copyFileWithTracking(ctx, src, join(destMindsDir, file));
  }
}

/** Step: Copy orchestration lib directory */
function installOrchestrationLib(ctx: CopyContext, mindsSourceDir: string, destMindsDir: string, log: LogFn): void {
  const libSrc = join(mindsSourceDir, "lib");
  if (existsSync(libSrc)) {
    copyDirRecursive(ctx, libSrc, join(destMindsDir, "lib"));
    log("  Copied orchestration lib");
  }
}

/** Step: Copy Claude Code slash commands into .claude/commands/ */
function installClaudeCommands(ctx: CopyContext, mindsSourceDir: string, repoRoot: string, log: LogFn): void {
  const claudeCommandsDir = join(repoRoot, ".claude", "commands");
  ensureDir(claudeCommandsDir);
  for (const { src: srcName, dest: destName } of CLAUDE_COMMANDS) {
    const src = join(mindsSourceDir, "commands", srcName);
    const dest = join(claudeCommandsDir, destName);
    if (!existsSync(src)) {
      log(`  Warning: Command file '${srcName}' not found at ${src}, skipping`);
      continue;
    }
    if (copyFileWithTracking(ctx, src, dest)) {
      log(`  Installed command: .claude/commands/${destName}`);
    }
  }
}

/** Step: Copy Claude Code skills into .claude/skills/ */
function installClaudeSkills(ctx: CopyContext, mindsSourceDir: string, repoRoot: string, log: LogFn): void {
  const skillsSrcDir = join(mindsSourceDir, "skills");
  if (!existsSync(skillsSrcDir)) return;
  const claudeSkillsDir = join(repoRoot, ".claude", "skills");
  ensureDir(claudeSkillsDir);
  for (const skillEntry of readdirSync(skillsSrcDir, { withFileTypes: true })) {
    if (!skillEntry.isDirectory()) continue;
    const skillSrc = join(skillsSrcDir, skillEntry.name);
    const skillDest = join(claudeSkillsDir, skillEntry.name);
    copyDirRecursive(ctx, skillSrc, skillDest);
    log(`  Installed skill: .claude/skills/${skillEntry.name}`);
  }
}

/** Step: Copy Claude Code hooks into .claude/hooks/ with chmod 755 */
function installClaudeHooks(ctx: CopyContext, mindsSourceDir: string, repoRoot: string, log: LogFn): void {
  const hooksSrcDir = join(mindsSourceDir, "hooks");
  if (!existsSync(hooksSrcDir)) return;
  const hookEntries = readdirSync(hooksSrcDir).filter(
    (name) => isHookFile(name) && !shouldSkipEntry(name)
  );
  if (hookEntries.length === 0) return;
  const claudeHooksDir = join(repoRoot, ".claude", "hooks");
  ensureDir(claudeHooksDir);
  for (const hookName of hookEntries) {
    const src = join(hooksSrcDir, hookName);
    const dest = join(claudeHooksDir, hookName);
    if (copyFileWithTracking(ctx, src, dest, { postCopy: (d) => chmodSync(d, 0o755) })) {
      log(`  Installed hook: .claude/hooks/${hookName}`);
    }
  }
}

/** Step: Generate/update tsconfig.json with @minds/* path alias */
function installTsconfig(ctx: CopyContext, repoRoot: string, log: LogFn): void {
  const tsconfigPath = join(repoRoot, "tsconfig.json");
  try {
    let tsconfig: Record<string, unknown> = {};
    if (existsSync(tsconfigPath)) {
      tsconfig = JSON.parse(readFileSync(tsconfigPath, "utf-8")) as Record<string, unknown>;
    }
    const compilerOptions = (tsconfig.compilerOptions ?? {}) as Record<string, unknown>;
    const paths = (compilerOptions.paths ?? {}) as Record<string, string[]>;
    paths["@minds/*"] = ["./.minds/*"];
    compilerOptions.paths = paths;
    tsconfig.compilerOptions = compilerOptions;
    writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2) + "\n");
    ctx.result.copied.push(relative(ctx.repoRoot, tsconfigPath));
    log("  Generated/updated tsconfig.json with @minds/* path alias");
  } catch (err) {
    ctx.result.errors.push(`tsconfig.json: ${(err as Error).message}`);
  }
}

/** Step: Populate .minds/minds.json from pre-generated core registry */
function installMindsRegistry(ctx: CopyContext, destMindsDir: string, log: LogFn): void {
  const mindsJsonPath = join(destMindsDir, "minds.json");
  const coreRegistryPath = join(dirname(_dir), "installer", "core-minds-registry.json");
  if (existsSync(coreRegistryPath)) {
    if (copyFileWithTracking(ctx, coreRegistryPath, mindsJsonPath)) {
      log("  Populated .minds/minds.json from core registry");
    }
  } else if (existsSync(mindsJsonPath) && !ctx.force) {
    // Core registry not available and target already exists — skip.
    // (copyFileWithTracking is not used here because there is no source file to copy.)
    ctx.result.skipped.push(relative(ctx.repoRoot, mindsJsonPath));
  } else {
    writeFileSync(mindsJsonPath, "[]\n");
    ctx.result.copied.push(relative(ctx.repoRoot, mindsJsonPath));
    log("  Generated .minds/minds.json registry placeholder (core registry not found)");
  }
}

/** Step: Verify Bun runtime and install CLI dependencies */
function verifyBunAndInstallDeps(ctx: CopyContext, destMindsDir: string, log: LogFn): void {
  const bunCheck = spawnSync("bun", ["--version"], { stdio: "ignore" });
  if (bunCheck.status === 0) {
    ctx.result.bunVerified = true;
    log("  Bun runtime verified");
  } else {
    ctx.result.errors.push("Bun runtime not found. Install Bun: https://bun.sh");
    return;
  }

  const mindsPackageJson = join(destMindsDir, "package.json");
  if (!existsSync(mindsPackageJson)) {
    writeFileSync(mindsPackageJson, JSON.stringify({
      name: "minds-runtime",
      version: "0.0.1",
      private: true,
    }, null, 2) + "\n");
    log("  Created .minds/package.json");
  }
  const addCmd = spawnSync("bun", ["add", "commander"], {
    cwd: destMindsDir,
    stdio: "pipe",
  });
  if (addCmd.status === 0) {
    log("  Installed commander dependency in .minds/");
  } else {
    const stderr = addCmd.stderr?.toString().trim() ?? "unknown error";
    ctx.result.errors.push(
      `Failed to install commander in .minds/ (run 'bun add commander' in .minds/ manually): ${stderr}`
    );
  }
}

/** Step: Register hooks in .claude/settings.json */
function installHookSettings(ctx: CopyContext, repoRoot: string, log: LogFn): void {
  const installedHookFiles = getInstalledHookFiles(join(repoRoot, ".claude", "hooks"));
  if (installedHookFiles.length === 0) return;
  try {
    const settingsPath = join(repoRoot, ".claude", "settings.json");
    const newSettings = generateClaudeSettings(installedHookFiles, settingsPath);
    const newContent = JSON.stringify(newSettings, null, 2) + "\n";

    if (!ctx.force && existsSync(settingsPath)) {
      const existingContent = readFileSync(settingsPath, "utf-8");
      if (existingContent === newContent) {
        ctx.result.skipped.push(relative(ctx.repoRoot, settingsPath));
        return;
      }
    }

    writeFileSync(settingsPath, newContent);
    ctx.result.copied.push(relative(ctx.repoRoot, settingsPath));
    log("  Generated/updated .claude/settings.json with hook registrations");
  } catch (err) {
    ctx.result.errors.push(`.claude/settings.json: ${(err as Error).message}`);
  }
}

/** Step: Build dashboard SPA */
function installDashboard(ctx: CopyContext, destMindsDir: string, log: LogFn): void {
  if (ctx.result.bunVerified) {
    const dashboardBuild = ensureDashboardBuilt(destMindsDir, true);
    if (dashboardBuild.skipped) {
      log("  Dashboard already built (or not present).");
    } else if (dashboardBuild.success) {
      ctx.result.dashboardBuilt = true;
      log("  Dashboard built successfully");
    } else {
      ctx.result.errors.push(`Dashboard build failed: ${dashboardBuild.error}`);
    }
  } else if (existsSync(join(destMindsDir, "dashboard", "package.json"))) {
    ctx.result.errors.push("Dashboard not built: Bun runtime not available");
  }
}

/** Step: Clone eval-factory as optional sibling dependency (non-blocking) */
function installEvalFactory(ctx: CopyContext, log: LogFn): void {
  const evalFactoryDir = join(ctx.repoRoot, "..", "eval-factory");
  if (existsSync(evalFactoryDir)) {
    log("  eval-factory: found at ../eval-factory, skipping clone");
    return;
  }

  log("  eval-factory: not found, cloning...");
  const cloneResult = spawnSync(
    "git",
    ["clone", "--depth", "1", "https://github.com/BrettHamlin/eval-factory.git", evalFactoryDir],
    { stdio: "pipe", timeout: 60_000 },
  );

  if (cloneResult.status !== 0) {
    const stderr = cloneResult.stderr?.toString().trim() ?? "unknown error";
    log(`  eval-factory: clone failed (non-fatal, eval-score stage will skip) — ${stderr}`);
    return;
  }

  // Install dependencies in the cloned eval-factory
  const installResult = spawnSync("bun", ["install"], {
    cwd: evalFactoryDir,
    stdio: "pipe",
    timeout: 60_000,
  });

  if (installResult.status === 0) {
    log("  eval-factory: cloned and dependencies installed");
  } else {
    log("  eval-factory: cloned but bun install failed (eval-score may not work)");
  }
}

/** Step: Install Axon daemon binary (non-blocking — failure does not halt init) */
async function installAxonBinary(ctx: CopyContext, destMindsDir: string, log: LogFn): Promise<void> {
  const binDir = join(destMindsDir, "bin");
  const installerDir = join(dirname(_dir), "installer");

  try {
    // Check if Axon is already installed and what version it is
    const versionCheck = await checkAxonVersion(ctx.repoRoot, installerDir);

    if (versionCheck.installed !== null && !versionCheck.needsUpgrade && !versionCheck.upgradeAvailable) {
      // Up to date — skip download
      log(`  Axon daemon: v${versionCheck.installed} (up to date)`);
      ctx.result.axonInstalled = true;
      return;
    }

    if (versionCheck.installed !== null && versionCheck.upgradeAvailable && !versionCheck.needsUpgrade) {
      // Optional upgrade available — log but still upgrade
      log(`  Axon upgrade available: v${versionCheck.installed} -> v${versionCheck.pinned}`);
    }

    if (versionCheck.installed !== null && versionCheck.needsUpgrade) {
      log(`  Axon daemon: v${versionCheck.installed} below minimum v${versionCheck.minVersion}, upgrading...`);
    }

    // Download the pinned version
    const version = getPinnedVersion(installerDir) ?? "0.1.0";
    const result = await installAxon({
      version,
      targetDir: binDir,
    });
    log(`  Axon daemon: installed v${result.version} (${getTargetTriple()})`);
    ctx.result.axonInstalled = true;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log(`  Axon daemon: download failed (tmux fallback available) — ${msg}`);
    ctx.result.axonInstalled = false;
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Copy core Minds and shared infrastructure to .minds/ in the target repo.
 * Generate tsconfig.json with @minds/* path alias.
 * Populate .minds/minds.json from pre-generated core registry.
 * Verify Bun runtime is installed.
 */
export async function installCoreMinds(
  mindsSourceDir: string,
  repoRoot: string,
  options: { force?: boolean; quiet?: boolean } = {}
): Promise<MindsInstallResult> {
  const { force = false, quiet = false } = options;
  const log: LogFn = quiet ? (..._args: unknown[]) => {} : console.log;
  const result: MindsInstallResult = { copied: [], skipped: [], errors: [], bunVerified: false, dashboardBuilt: false, axonInstalled: false };
  const ctx: CopyContext = { force, repoRoot, result };

  const destMindsDir = join(repoRoot, ".minds");
  ensureDir(destMindsDir);

  // Phase 1: Copy source files
  installCoreMindDirs(ctx, mindsSourceDir, destMindsDir, log);
  installSharedInfraDirs(ctx, mindsSourceDir, destMindsDir, log);
  installSharedInfraFiles(ctx, mindsSourceDir, destMindsDir, log);
  installOrchestrationLib(ctx, mindsSourceDir, destMindsDir, log);

  // Phase 2: Claude Code integration
  installClaudeCommands(ctx, mindsSourceDir, repoRoot, log);
  installClaudeSkills(ctx, mindsSourceDir, repoRoot, log);
  installClaudeHooks(ctx, mindsSourceDir, repoRoot, log);

  // Phase 3: Configuration
  installTsconfig(ctx, repoRoot, log);
  installMindsRegistry(ctx, destMindsDir, log);

  // Phase 4: Runtime setup
  verifyBunAndInstallDeps(ctx, destMindsDir, log);
  installHookSettings(ctx, repoRoot, log);
  installDashboard(ctx, destMindsDir, log);

  // Phase 5: Axon daemon binary (non-blocking)
  await installAxonBinary(ctx, destMindsDir, log);

  // Phase 6: Optional eval-factory dependency (non-blocking)
  installEvalFactory(ctx, log);

  return result;
}
