/**
 * Spec viewing API routes
 */

import { Router, Request, Response } from 'express';
import { asyncHandler } from '../middleware.js';
import { callEngine } from '../engine.js';
import { validateUUID } from '../../shared/validation.js';
import { NotFoundError } from '../../shared/errors.js';

const router = Router();

// GET /api/spec/{id}
router.get('/:id', asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;
  const { format } = req.query;

  validateUUID(id);

  const spec = await callEngine<{
    id: string; title: string; description: string; state: string;
    pmUserId: string; pmDisplayName?: string; complexityScore: number;
    totalQuestions: number; answeredQuestions: number;
    content?: string; contentHtml?: string;
    createdAt: Date; updatedAt: Date;
    channel?: unknown;
    roles: Array<{ name: string; rationale: string; members: unknown[] }>;
  }>('get spec', { specId: id });

  if (!spec) {
    throw new NotFoundError('Spec not found');
  }

  if (format === 'html') {
    // Return full HTML page
    const htmlPage = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${spec.title} - SpecFactory</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #333; padding: 20px; background: #f5f5f5; }
    .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    h1 { font-size: 2.5em; margin-bottom: 0.5em; color: #1a1a1a; }
    h2 { font-size: 1.8em; margin-top: 1.5em; margin-bottom: 0.5em; color: #2a2a2a; border-bottom: 2px solid #e0e0e0; padding-bottom: 0.3em; }
    h3 { font-size: 1.4em; margin-top: 1.2em; margin-bottom: 0.5em; color: #3a3a3a; }
    p { margin-bottom: 1em; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-family: monospace; }
    pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; margin: 1em 0; }
    pre code { background: none; padding: 0; }
    ul, ol { margin-left: 2em; margin-bottom: 1em; }
    li { margin-bottom: 0.5em; }
    table { border-collapse: collapse; width: 100%; margin: 1em 0; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
    th { background: #f8f8f8; font-weight: 600; }
    .metadata { background: #f8f9fa; padding: 20px; border-radius: 5px; margin-bottom: 30px; font-size: 0.9em; }
    .metadata strong { color: #555; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; text-align: center; color: #888; font-size: 0.9em; }
    @media print { body { background: white; padding: 0; } .container { box-shadow: none; } }
  </style>
</head>
<body>
  <div class="container">
    <h1>${spec.title}</h1>
    <div class="metadata">
      <p><strong>Created by:</strong> ${spec.pmDisplayName || 'PM'}</p>
      <p><strong>Created:</strong> ${new Date(spec.createdAt).toLocaleDateString()}</p>
      <p><strong>Complexity Score:</strong> ${spec.complexityScore}/10</p>
      <p><strong>Questions Answered:</strong> ${spec.answeredQuestions}/${spec.totalQuestions}</p>
    </div>
    ${spec.contentHtml || '<p><em>Specification content is being generated...</em></p>'}
    <div class="footer">
      <p>Generated by SpecFactory | <a href="${process.env.SPEC_BASE_URL}">specfactory.app</a></p>
    </div>
  </div>
</body>
</html>`;

    res.set('Content-Type', 'text/html').send(htmlPage);
  } else {
    // Return JSON
    res.json({
      id: spec.id,
      title: spec.title,
      description: spec.description,
      state: spec.state,
      pmUserId: spec.pmUserId,
      pmDisplayName: spec.pmDisplayName,
      complexityScore: spec.complexityScore,
      totalQuestions: spec.totalQuestions,
      answeredQuestions: spec.answeredQuestions,
      content: spec.content,
      contentHtml: spec.contentHtml,
      createdAt: spec.createdAt,
      updatedAt: spec.updatedAt,
      channel: spec.channel,
      roles: spec.roles.map(role => ({
        name: role.name,
        rationale: role.rationale,
        members: role.members,
      })),
    });
  }
}));

export default router;
